### PR TITLE
bumped deps and added node 8

### PR DESCRIPTION
**Pull request by mcollina**
cc @jmatsushita please have a look as tests are failing due to the updated deps.

### CODE REVIEW

**Comment by jmatsushita** [comment]
This issue jsonld.js#167 requires us to stay pinned at `jsonld@0.4.9`

**Comment by mcollina** [comment]
I just pushed, but the tests are still not passing.

**Comment by jmatsushita** [comment]
Which ones aren't passing? 

image

**Comment by mcollina** [comment]
```
 1) IRI keeps @id as IRI
```

But it might have been flaky, it's passing now.

**Comment by jmatsushita** [comment]
Cool.There’s some potential url resolution going on there if I recall, so that might be what makes it flaky.

--
Jun Matsushita 
Founder, CEO
iilab - information innovation lab -  iilab.org  - @iilab

cell +49 157 530 86174
xmpp jun@jabber.ccc.de  
pgp D38A 5502 7387 3BF4 B330  7DA2 2A07 F70C A036 E792

**Pull request merged**
